import * as yup from 'yup';

// Identity verification metadata schema
export const identityVerificationMetadataSchema = yup.object({
  documentType: yup
    .string()
    .oneOf(['passport', 'aadhaar', 'drivers_license', 'national_id'])
    .required('Document type is required'),
  documentNumber: yup.string().required('Document number is required'),
  documentUrls: yup
    .array()
    .of(yup.string().url('Must be a valid URL'))
    .min(1, 'At least one document URL is required')
    .required('Document URLs are required'),
  facePhotoUrl: yup.string().url('Must be a valid URL').optional(),
  expiryDate: yup.date().optional(),
});

// Role verification metadata schema for Investors
export const investorRoleMetadataSchema = yup.object({
  proofType: yup
    .string()
    .oneOf(['proof_of_funds', 'accreditation', 'portfolio', 'tax_documents'])
    .required('Proof type is required'),
  proofUrls: yup
    .array()
    .of(yup.string().url('Must be a valid URL'))
    .min(1, 'At least one proof document is required')
    .required('Proof documents are required'),
  accreditationNumber: yup.string().optional(),
  fundAmount: yup.number().positive().optional(),
  investmentHistory: yup.string().optional(),
});

// Role verification metadata schema for Startups
export const startupRoleMetadataSchema = yup.object({
  proofType: yup
    .string()
    .oneOf(['incorporation_certificate', 'business_registration', 'pitch_deck', 'gst_certificate'])
    .required('Proof type is required'),
  proofUrls: yup
    .array()
    .of(yup.string().url('Must be a valid URL'))
    .min(1, 'At least one proof document is required')
    .required('Proof documents are required'),
  incorporationNumber: yup.string().optional(),
  incorporationDate: yup.date().optional(),
  registrationNumber: yup.string().optional(),
  gstNumber: yup.string().optional(),
});

// Activity verification metadata schema
export const activityVerificationMetadataSchema = yup.object({
  score: yup
    .number()
    .min(0, 'Score must be at least 0')
    .max(100, 'Score cannot exceed 100')
    .required('Activity score is required'),
  metrics: yup.object().optional(),
  autoGenerated: yup.boolean().default(true),
});

// Community verification metadata schema
export const communityVerificationMetadataSchema = yup.object({
  trustScore: yup
    .number()
    .min(0, 'Trust score must be at least 0')
    .max(100, 'Trust score cannot exceed 100')
    .required('Trust score is required'),
  reviewCount: yup.number().min(0).optional(),
  averageRating: yup.number().min(0).max(5).optional(),
  autoGenerated: yup.boolean().default(true),
});

// Submit verification stage schema
export const submitVerificationStageSchema = yup.object({
  type: yup
    .string()
    .oneOf(['IDENTITY', 'ROLE', 'ACTIVITY', 'COMMUNITY'])
    .required('Verification type is required'),
  metadata: yup
    .object()
    .required('Metadata is required')
    .test('metadata-validation', 'Invalid metadata for verification type', function (value) {
      const { type } = this.parent;

      try {
        switch (type) {
          case 'IDENTITY':
            identityVerificationMetadataSchema.validateSync(value);
            break;
          case 'ROLE':
            // We can't validate role-specific without knowing user role here
            // This will be validated in the service layer
            break;
          case 'ACTIVITY':
            activityVerificationMetadataSchema.validateSync(value);
            break;
          case 'COMMUNITY':
            communityVerificationMetadataSchema.validateSync(value);
            break;
        }
        return true;
      } catch (error) {
        return this.createError({
          message: error instanceof Error ? error.message : 'Invalid metadata',
        });
      }
    }),
});

// Review verification stage schema
export const reviewVerificationStageSchema = yup.object({
  stageId: yup.string().uuid('Must be a valid UUID').required('Stage ID is required'),
  status: yup.string().oneOf(['APPROVED', 'REJECTED']).required('Status is required'),
  reviewNote: yup.string().max(1000, 'Review note cannot exceed 1000 characters').optional(),
});
