import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientOnlyLayout from './ClientOnlyLayout';
import { ThemeProvider } from '@/components/layout/ThemeProvider';
import Sonner from '@/components/ui/sonner';
import { AuthProvider } from '@/context/authContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <ThemeProvider>
            <Sonner />
            <ClientOnlyLayout>{children}</ClientOnlyLayout>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
